[env]
TERM = "alacritty"
COLORTERM = "truecolor"

[window]
decorations = "None"
dynamic_padding = true
resize_increments = true
opacity = 0.82                # Sweet spot: visible but not distracting
startup_mode = "Windowed"
dimensions = { columns = 88, lines = 24 }  # Golden ratio-ish proportions
option_as_alt = "Both"        # Essential for vim/tmux workflows
blur = true                   # Enable background blur (compositor dependent)

[window.padding]
x = 20                        # Breathing room for readability
y = 16                        # Vertical balance

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 100000              # Massive history for development
multiplier = 4                # Swift scrolling
auto_scroll = true            # Follow output automatically

[font]
size = 12.5                   # Slightly larger for better readability
builtin_box_drawing = true    # Crisp borders and UI elements
# Anti-aliasing for smoother text rendering
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"                # Less aggressive than ExtraBold

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Micro-adjustments for pixel-perfect typography
[font.offset]
x = 0
y = 1                         # Subtle baseline adjustment

[font.glyph_offset]
x = 0
y = 0                         # Perfect glyph alignment

[cursor]
blink_interval = 800          # Calm, rhythmic blinking
blink_timeout = 10            # Stop blinking after 10s of inactivity
thickness = 0.12              # Ultra-thin beam for precision
unfocused_hollow = true       # Subtle unfocused state
vi_mode_style = "Block"       # Clear mode indication

[cursor.style]
blinking = "On"
shape = "Beam"


[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true   # Better transparency handling
indexed_colors = [
  # Extended palette for advanced color schemes
  { index = 16, color = "#ff9e64" },   # Orange
  { index = 17, color = "#db4b4b" },   # Dark red
  { index = 18, color = "#1a1b26" },   # Background alt
  { index = 19, color = "#414868" },   # Comment
  { index = 20, color = "#c0caf5" },   # Foreground alt
  { index = 21, color = "#a9b1d6" },   # Foreground dim
]

[colors.primary]
background = "#16161e"        # Slightly darker for better contrast
foreground = "#c0caf5"        # Crisp white-blue
bright_foreground = "#ffffff" # Pure white for highlights
dim_foreground = "#9aa5ce"    # Muted for less important text

# Elegant selection with subtle glow effect
[colors.selection]
text = "CellBackground"
background = "#283457"        # Deeper blue selection

# Search highlighting with TokyoNight accent
[colors.search.matches]
foreground = "#16161e"
background = "#ff9e64"        # Orange highlight

[colors.search.focused_match]
foreground = "#16161e"
background = "#7aa2f7"        # Blue focused match

# URL and path hints with themed colors
[colors.hints.start]
foreground = "#16161e"
background = "#e0af68"        # Yellow start

[colors.hints.end]
foreground = "#16161e"
background = "#73daca"        # Cyan end

# Vi mode indicators
[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#16161e"
background = "#7aa2f7"        # Blue footer

# Core color palette - enhanced TokyoNight
[colors.normal]
black   = "#15161e"           # True black
red     = "#f7768e"           # Coral red
green   = "#9ece6a"           # Matrix green
yellow  = "#e0af68"           # Warm yellow
blue    = "#7aa2f7"           # Sky blue
magenta = "#bb9af7"           # Purple
cyan    = "#7dcfff"           # Bright cyan
white   = "#a9b1d6"           # Off-white

[colors.bright]
black   = "#414868"           # Dark gray
red     = "#ff7a93"           # Bright coral
green   = "#b9f27c"           # Bright green
yellow  = "#ff9e64"           # Orange-yellow
blue    = "#7da6ff"           # Bright blue
magenta = "#c0a4ff"           # Bright purple
cyan    = "#b4e6ff"           # Bright cyan
white   = "#c0caf5"           # Bright white

# Dimmed colors for subtle text
[colors.dim]
black   = "#0f0f14"
red     = "#e06b75"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#828bb1"

[bell]
animation = "EaseOutExpo"     # Smooth animation curve
color = "#bb9af7"             # Purple flash
duration = 200                # Slightly longer for visibility
command = "None"              # No sound, just visual

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right",  action = "PasteSelection" },
  # Ctrl+click for URL opening
  { mouse = "Left", mods = "Control", action = "FollowLinkAtCursor" },
]

[hints]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-\u009f<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true
mouse.mods = "None"
binding.key = "U"
binding.mods = "Control|Shift"

[[hints.enabled]]
regex = "(\\.|~|\\$HOME)?(/[\\w\\d\\-.]+)+/?"
command = "xdg-open"
post_processing = true
mouse.enabled = true
mouse.mods = "Control"
binding.key = "F"
binding.mods = "Control|Alt"

[[hints.enabled]]
regex = "\\b[0-9a-f]{7,40}\\b"
mouse.enabled = true
mouse.mods = "Control"
binding.key = "G"
binding.mods = "Control|Shift"


[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l"] }  # Login shell for proper env
osc52 = "CopyPaste"           # Better clipboard integration

[general]
live_config_reload = true

# Core clipboard operations
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

# Font size controls with more granular steps
[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

# Window management
[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "ToggleViMode"

# Enhanced search with regex support
[[keyboard.bindings]]
key = "F"
mods = "Control"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control"
action = "SearchBackward"

# Advanced terminal spawning
[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
command = { 
  program = "alacritty", 
  args = [
    "--working-directory", ".",
    "-e", "zsh", "-c", 
    "exec tmux new-session -A -D -s main \\; set-option -g status-style 'bg=#1a1b26,fg=#7aa2f7'"
  ] 
}

# Quick terminal with current directory
[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
command = { program = "alacritty", args = ["--working-directory", "."] }

# Enhanced scrolling with vim-like navigation
[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "U"
mods = "Control|Shift"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "G"
mods = "Control|Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "G"
mods = "Control|Alt"
action = "ScrollToBottom"

# Clear screen and scrollback
[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control|Alt"
action = "ClearHistory"

# Word navigation (shell-agnostic)
[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001bb"             # Alt+b (backward word)

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001bf"             # Alt+f (forward word)

# Line navigation
[[keyboard.bindings]]
key = "Left"
mods = "Control|Shift"
chars = "\u0001"              # Ctrl+a (beginning of line)

[[keyboard.bindings]]
key = "Right"
mods = "Control|Shift"
chars = "\u0005"              # Ctrl+e (end of line)

# Advanced deletion
[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u0017"              # Ctrl+w (delete word)

[[keyboard.bindings]]
key = "Delete"
mods = "Control"
chars = "\u001bd"             # Alt+d (delete word forward)

# Process control
[[keyboard.bindings]]
key = "C"
mods = "Control"
chars = "\u0003"              # Ctrl+c (SIGINT)

[[keyboard.bindings]]
key = "Z"
mods = "Control"
chars = "\u001a"              # Ctrl+z (SIGTSTP)

# History navigation enhancement
[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[A"            # Enhanced up arrow

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[B"            # Enhanced down arrow

# Tab management for tmux users
[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u0001c"             # Tmux: new window

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u0001x"             # Tmux: kill pane

# Pane navigation shortcuts
[[keyboard.bindings]]
key = "H"
mods = "Control|Alt"
chars = "\u0001h"             # Tmux: left pane

[[keyboard.bindings]]
key = "L"
mods = "Control|Alt"
chars = "\u0001l"             # Tmux: right pane

[[keyboard.bindings]]
key = "K"
mods = "Control|Alt"
chars = "\u0001k"             # Tmux: up pane

[[keyboard.bindings]]
key = "J"
mods = "Control|Alt"
chars = "\u0001j"             # Tmux: down pane

# Quick directory operations
[[keyboard.bindings]]
key = "Period"
mods = "Control|Shift"
chars = "cd ..\r"             # Quick parent directory

# Vi-mode enhancements
[[keyboard.bindings]]
key = "Escape"
action = "ToggleViMode"

# Vi-mode specific bindings
[[keyboard.bindings]]
key = "I"
mode = "Vi"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "I"
mode = "Vi"
action = "ToggleViMode"
