# Alacritty Configuration v0.16 dev
# Optimized for performance, TokyoNight theme, tmux integration

# Global settings
general.live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "alacritty"
COLORTERM = "truecolor"

# Window Configuration
[window]
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_padding = true
resize_increments = true
opacity = 0.80
startup_mode = "Windowed"
dimensions = { columns = 89, lines = 24 }

[window.padding]
x = 22
y = 18

[window.class]
instance = "Alacritty"
general = "Alacritty"

# Font Configuration
[font]
size = 12
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

# Cursor Configuration
[cursor]
blink_interval = 500
blink_timeout = 5
thickness = 0.12
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Beam"

# Scrolling
[scrolling]
history = 10000
multiplier = 4

# Selection
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# Bell
[bell]
animation = "EaseOutExpo"
color = "#bb9af7"
duration = 180
command = "None"

# Terminal
[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

# Colors - TokyoNight Theme
[colors]
draw_bold_text_with_bright_colors = true

# Extended palette for sophisticated theming
indexed_colors = [
  { index = 16, color = "#ff9e64" },   # Sunset orange
  { index = 17, color = "#db4b4b" },   # Deep crimson
  { index = 18, color = "#1a1b26" },   # Midnight alternative
  { index = 19, color = "#414868" },   # Charcoal commentary
  { index = 20, color = "#c0caf5" },   # Crystal foreground
  { index = 21, color = "#a9b1d6" },   # Moonlit text
  { index = 22, color = "#7aa2f7" },   # Electric blue accent
  { index = 23, color = "#bb9af7" },   # Mystical purple
]

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"
dim_foreground = "#9aa5ce"

[colors.selection]
text = "#1a1b26"
background = "#364A82"

[colors.search.matches]
foreground = "#1a1b26"
background = "#ff9e64"

[colors.search.focused_match]
foreground = "#1a1b26"
background = "#7aa2f7"

[colors.hints.start]
foreground = "#1a1b26"
background = "#e0af68"

[colors.hints.end]
foreground = "#1a1b26"
background = "#7dcfff"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#ff7a93"
green   = "#b9f27c"
yellow  = "#ff9e64"
blue    = "#7da6ff"
magenta = "#c0a4ff"
cyan    = "#b4e6ff"
white   = "#c0caf5"

[colors.dim]
black   = "#0f0f14"
red     = "#e06b75"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#828bb1"

# Mouse Configuration
[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

[[mouse.bindings]]
mouse = "Forward"
mods = "Control"
action = "IncreaseFontSize"

[[mouse.bindings]]
mouse = "Back"
mods = "Control"
action = "DecreaseFontSize"

# Hints Configuration
[[hints.enabled]]
regex = "(https?|ftp|file|git|ssh)://[^\\s<>\"{}|\\^`\\[\\]]+"
action = "Copy"
mouse = { enabled = true, mods = "None" }
binding = { key = "U", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(https?|ftp)://[^\\s<>\"{}|\\^`\\[\\]]+"
command = "xdg-open"
post_processing = true
mouse = { enabled = true, mods = "Control" }
binding = { key = "O", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(\\.|~)?/[\\w\\d\\-._/]+"
action = "Copy"
mouse = { enabled = true, mods = "Control" }
binding = { key = "P", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(?-u)\\b[0-9a-f]{7,40}\\b"
action = "Copy"
mouse = { enabled = true, mods = "Control" }
binding = { key = "H", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(?-u)\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"
action = "Copy"
mouse = { enabled = true, mods = "Control" }
binding = { key = "I", mods = "Control|Shift" }

# Keyboard Bindings
# Essential clipboard operations
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

# Dynamic font scaling
[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

# Window management
[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ToggleFullscreen"

# Search capabilities
[[keyboard.bindings]]
key = "F"
mods = "Control"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control"
action = "SearchBackward"

[[keyboard.bindings]]
key = "G"
mods = "Control"
action = "SearchNext"

[[keyboard.bindings]]
key = "G"
mods = "Control|Shift"
action = "SearchPrevious"

# Vi mode
[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "ToggleViMode"

# Smart terminal spawning with tmux integration
[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
[keyboard.bindings.command]
program = "alacritty"
args = [
  "--working-directory", ".",
  "-e", "zsh", "-c",
  "exec tmux new-session -A -D -s main \\; set-option -g status-style 'bg=#1a1b26,fg=#7aa2f7'"
]

# Quick new terminal instance
[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
[keyboard.bindings.command]
program = "alacritty"
args = ["--working-directory", "."]

# Vim-inspired navigation
[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "U"
mods = "Control|Shift"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Control"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Control"
action = "ScrollToBottom"

# Screen clearing
[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control|Alt"
action = "ClearHistory"

# Enhanced word navigation
[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001bf"

# Line boundary navigation
[[keyboard.bindings]]
key = "Left"
mods = "Control|Shift"
chars = "\u0001"

[[keyboard.bindings]]
key = "Right"
mods = "Control|Shift"
chars = "\u0005"

# Advanced text deletion
[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u0017"

[[keyboard.bindings]]
key = "Delete"
mods = "Control"
chars = "\u001bd"

# Process control
[[keyboard.bindings]]
key = "C"
mods = "Control"
chars = "\u0003"

[[keyboard.bindings]]
key = "Z"
mods = "Control"
chars = "\u001a"

# Enhanced history navigation
[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[A"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[B"

# Tmux integration
[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u0001c"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u0001n"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u0001p"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u0001x"

# Tmux pane navigation 
[[keyboard.bindings]]
key = "H"
mods = "Control|Alt"
chars = "\u0001h"

[[keyboard.bindings]]
key = "L"
mods = "Control|Alt"
chars = "\u0001l"

[[keyboard.bindings]]
key = "K"
mods = "Control|Alt"
chars = "\u0001k"

[[keyboard.bindings]]
key = "J"
mods = "Control|Alt"
chars = "\u0001j"

# Tmux pane splitting
[[keyboard.bindings]]
key = "Backslash"
mods = "Control|Shift"
chars = "\u0001\\"

[[keyboard.bindings]]
key = "Minus"
mods = "Control|Shift"
chars = "\u0001-"

# Tmux session management
[[keyboard.bindings]]
key = "S"
mods = "Control|Shift"
chars = "\u0001s"

# Quick directory navigation
[[keyboard.bindings]]
key = "Period"
mods = "Control|Shift"
chars = "cd ..\r"
