[env]
WINIT_X11_SCALE_FACTOR = "1.0" 

TERM = "alacritty"
COLORTERM = "truecolor"

# Window Configuration
[window]
decorations = "none"          # A clean window
dynamic_padding = true        # Intelligent space management
resize_increments = true      # Precise resizing control
opacity = 0.75            
startup_mode = "Windowed"    
dimensions = { columns = 89, lines = 24 }  
option_as_alt = "Both"

[window.padding]
x = 22                        
y = 18                        

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 30000               # Vast history for power users
multiplier = 4                # Smooth, controlled scrolling

[font]
size = 12                     
builtin_box_drawing = true    # Crisp UI elements and borders

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"        

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"                

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"              

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"        

# Micro-adjustments for typographic perfection
[font.offset]
x = 0
y = 1                         # Subtle baseline optimization

[font.glyph_offset]
x = 0
y = 0                        

[cursor]
blink_interval = 650          # Hypnotic rhythm
blink_timeout = 8             
thickness = 0.15              # Refined beam thickness
unfocused_hollow = true       # Subtle focus indication
vi_mode_style = "Block"       

[cursor.style]
blinking = "On"
shape = "Beam"               

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true  

# Extended palette for sophisticated theming
indexed_colors = [
  { index = 16, color = "#ff9e64" },   # Sunset orange
  { index = 17, color = "#db4b4b" },   # Deep crimson
  { index = 18, color = "#1a1b26" },   # Midnight alternative
  { index = 19, color = "#414868" },   # Charcoal commentary
  { index = 20, color = "#c0caf5" },   # Crystal foreground
  { index = 21, color = "#a9b1d6" },   # Moonlit text
  { index = 22, color = "#7aa2f7" },   # Electric blue accent
  { index = 23, color = "#bb9af7" },   # Mystical purple
  { index = 24, color = "#2ac3de" },   # Neon cyan
  { index = 25, color = "#ff7a93" },   # Rose 
  { index = 26, color = "#73daca" },   # Mint green
  { index = 27, color = "#e0af68" },   # Golden amber
]

[colors.primary]
background = "#1a1b26"        # Deep night sky backdrop
foreground = "#c0caf5"        # Crystalline blue-white text
dim_foreground = "#9aa5ce"    # Elegant muted text

# Sophisticated selection with glow effect
[colors.selection]
text = "CellBackground"
background = "#364A82"        # Rich sapphire selection

# Search highlighting with thematic harmony
[colors.search.matches]
foreground = "#1a1b26"
background = "#e0af68"        # Golden honey highlight

[colors.search.focused_match]
foreground = "#1a1b26"
background = "#7aa2f7"        # Electric focus

# Elegant hint styling with color coordination
[colors.hints.start]
foreground = "#1a1b26"
background = "#e0af68"        # Warm gold start

[colors.hints.end]
foreground = "#1a1b26"
background = "#7dcfff"        # Crystal cyan end

# Core TokyoNight palette - artistically refined
[colors.normal]
black   = "#15161e"           # Void black
red     = "#f7768e"           # Coral passion
green   = "#9ece6a"           # Forest emerald
yellow  = "#e0af68"           # Golden amber
blue    = "#7aa2f7"           # Electric sapphire
magenta = "#bb9af7"           # Lavender dreams
cyan    = "#7dcfff"           # Crystal aqua
white   = "#a9b1d6"           # Moonstone

[colors.bright]
black   = "#414868"           # Storm cloud
red     = "#ff7a93"           # Bright coral
green   = "#b9f27c"           # Vivid lime
yellow  = "#ff9e64"           # Sunset orange
blue    = "#7da6ff"           # Brilliant azure
magenta = "#c0a4ff"           # Bright orchid
cyan    = "#b4e6ff"           # Luminous cyan
white   = "#c0caf5"           # Pure crystal

# Dimmed palette for subtle elegance
[colors.dim]
black   = "#0f0f14"           # Deep shadow
red     = "#e06b75"           # Muted rose
green   = "#98c379"           # Sage green
yellow  = "#d19a66"           # Antique brass
blue    = "#61afef"           # Dusty blue
magenta = "#c678dd"           # Faded violet
cyan    = "#56b6c2"           # Soft teal
white   = "#828bb1"           # Silver mist

[bell]
animation = "EaseOutExpo"     # Silky smooth animation
color = "#bb9af7"             # Signature purple flash
duration = 180                # Brief, non-intrusive
command = "None"              

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true  
bindings = [
  { mouse = "Right", action = "PasteSelection" },
  { mouse = "Forward", mods = "Control", action = "IncreaseFontSize" },
  { mouse = "Back", mods = "Control", action = "DecreaseFontSize" },
]

[hints]

# Clickable URL detection
[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+"
action = "Copy"
mouse = { enabled = true, mods = "None" }
binding = { key = "U", mods = "Control|Shift" }

# Enhanced path detection
[[hints.enabled]]
regex = "(\\.|~|\\$HOME)?(/[\\w\\d\\-._]+)+/?"
action = "Copy"
mouse = { enabled = true, mods = "Control" }
binding = { key = "P", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(?:^|\\s)([0-9a-f]{7,40})(?=\\s|$|[:;,\\.])"
action = "Copy"
mouse = { enabled = true, mods = "Control" }
binding = { key = "G", mods = "Control|Shift" }

# IPv4 address detection
[[hints.enabled]]
regex = "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"
action = "Copy"
mouse = { enabled = true, mods = "Control" }
binding = { key = "I", mods = "Control|Shift" }

[terminal]
osc52 = "CopyPaste"           # Advanced clipboard integration

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

# Essential clipboard operations
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

# Dynamic font scaling
[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

# Window management excellence
[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "ToggleViMode"

# Advanced Search capabilities
[[keyboard.bindings]]
key = "F"
mods = "Control"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control"
action = "SearchBackward"

# Smart terminal spawning with tmux integration
[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
[keyboard.bindings.command]
program = "alacritty"
args = [
  "--working-directory", ".",
  "-e", "zsh", "-c",
  "exec tmux new-session -A -D -s main \\; set-option -g status-style 'bg=#1a1b26,fg=#7aa2f7'"
]

# Quick new terminal instance
[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
[keyboard.bindings.command]
program = "alacritty"
args = ["--working-directory", "."]

# Vim-inspired navigation excellence
[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "U"
mods = "Control|Shift"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Control"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Control"
action = "ScrollToBottom"

# Screen management and clearing
[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control|Alt"
action = "ClearHistory"

# Vi-mode enhancements
[[keyboard.bindings]]
key = "Escape"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "I"
mode = "Vi"
action = "ToggleViMode"

# Enhanced word navigation
[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001bb"             # Alt+b (backward word)

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001bf"             # Alt+f (forward word)

# Line boundary navigation
[[keyboard.bindings]]
key = "Left"
mods = "Control|Shift"
chars = "\u0001"              # Ctrl+a (beginning of line)

[[keyboard.bindings]]
key = "Right"
mods = "Control|Shift"
chars = "\u0005"              # Ctrl+e (end of line)

# Advanced text deletion
[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u0017"              # Ctrl+w (delete word)

[[keyboard.bindings]]
key = "Delete"
mods = "Control"
chars = "\u001bd"             # Alt+d (delete word forward)

# Process control commands
[[keyboard.bindings]]
key = "C"
mods = "Control"
chars = "\u0003"              # Ctrl+c (SIGINT)

[[keyboard.bindings]]
key = "Z"
mods = "Control"
chars = "\u001a"              # Ctrl+z (SIGTSTP)

# Enhanced history navigation
[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[A"            # Refined up arrow

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[B"            # Refined down arrow

# Tmux integration mastery
[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u0001c"             # Tmux: new window

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u0001n"             # Tmux next window

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u0001p"             # Tmux previous window

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u0001x"             # Tmux: kill pane

# Tmux pane navigation shortcuts
[[keyboard.bindings]]
key = "H"
mods = "Control|Alt"
chars = "\u0001h"             # Tmux: left pane

[[keyboard.bindings]]
key = "L"
mods = "Control|Alt"
chars = "\u0001l"             # Tmux: right pane

[[keyboard.bindings]]
key = "K"
mods = "Control|Alt"
chars = "\u0001k"             # Tmux: up pane

[[keyboard.bindings]]
key = "J"
mods = "Control|Alt"
chars = "\u0001j"             # Tmux: down pane

# Quick directory navigation
[[keyboard.bindings]]
key = "Period"
mods = "Control|Shift"
chars = "cd ..\r"             # Parent directory shortcut

# Better search navigation
[[keyboard.bindings]]
key = "G"
mods = "Control"
action = "SearchNext"

[[keyboard.bindings]]
key = "G"
mods = "Control|Shift"
action = "SearchPrevious"